# Generated by Django 3.0.2 on 2020-01-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bathroomapp', '0002_bids_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bathroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathroomId', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('gender', models.CharField(max_length=6)),
                ('numStall', models.IntegerField()),
                ('numUrinal', models.IntegerField()),
                ('ratingOverall', models.IntegerField()),
                ('ratingClean', models.IntegerField()),
                ('ratingConv', models.IntegerField()),
            ],
        ),
    ]
