# Generated by Django 3.0.2 on 2020-01-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bathroomapp', '0003_bathroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathroom',
            name='reqCode',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='bathroom',
            name='securityCode',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
