# Generated by Django 3.0.2 on 2020-01-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bathroomapp', '0004_auto_20200125_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathroom',
            name='reqCode',
            field=models.CharField(max_length=3),
        ),
    ]
